### PR TITLE
Rename the `julia-version` input to `channel`

### LINKED ISSUE #59: Should we use `juliaup-channel` (or just `channel`) instead of `julia-version`?
The language in Juliaup world is pretty consistent, i.e. that we call that "channel"...

### PR DESCRIPTION
**Pull request by DilumAluthge**
Fixes #59

This is a breaking change.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@davidanthoff I went with `channel` here, but if you prefer, I can rename it to `juliaup-channel`.

**Comment by davidanthoff** [comment]
I think `channel` makes the most sense. The only time we add `julia` to that name is for the env var `JULIAUP_CHANNEL`, but that is only because it is essentially a global namespace. Everywhere else where it is clear that things are in the Juliaup context, we just use `channel`, so I think that makes most sense here as well. So: thumbs up :)

**Review by davidanthoff — APPROVED** [review]

**Comment by DilumAluthge** [comment]
I'll hold off on merging this until we decide if there any other breaking changes we want to make. Then we can make a single breaking release that includes all of the breaking changes in a single release.

**Comment by DilumAluthge** [comment]
@davidanthoff Shall we merge this now, and tag a breaking `v2`?

Are there any other breaking changes that we want to include in `v2`?

**Comment by davidanthoff** [comment]
Looks good to me, I'd say lets merge and do a v2! I can't think of any other breaking things right now.

**Comment by DilumAluthge** [comment]
I'll create the `v2.0.0` and `v2` tags.

**Comment by DilumAluthge** [comment]
My TODO list:

- [ ] Create the `v2.0.0` tag and corresponding GitHub Release
- [ ] Create the `v2` tag (that just points to the `v2.0.0` tag
- [ ] Update the README to replace all occurrences of `v1` with `v2`

**Comment by DilumAluthge** [comment]
I have finished the tasks in my above TODO list.

**Pull request merged**
